frame_id: base_link

default_orientation:
  x: 0.0
  y: 0.70710678
  z: 0.0
  w: 0.70710678

open_before_start: true
settle_time_sec: 0.5

gripper:
  open_position: 0.0
  closed_position: 1.18
  grasp_force_n: 10.0
  release_force_n: 5.0

points:
  point_1:
    x: 0.300
    y: -0.200
    z: 0.300
  point_2:
    x: 0.300
    y: -0.200
    z: 0.120
  point_3:
    x: 0.450
    y: 0.150
    z: 0.300
  point_4:
    x: 0.450
    y: 0.150
    z: 0.120
