#!/usr/bin/env python3

import rclpy
from rclpy.node import Node
from onrobot_rg_msgs.msg import OnRobotRGInput


def printStatus(node, status):
    """Prints the status string generated by the statusInterpreter function."""

    node.get_logger().info(statusInterpreter(status))  
#----------------------------------------------------------
class OnRobotRGStatusListener(Node):
    """Initializes the node and subscribe to the OnRobotRGInput topic."""

    def __init__(self):
        super().__init__('OnRobotRGStatusListener')
        self.subscription = self.create_subscription(
            OnRobotRGInput,
            'OnRobotRGInput',
            self.listener_callback,
            10)
        self.subscription  # prevent unused variable warning
#----------------------------------------------------------
    def listener_callback(self, status):
        printStatus(self, status)

#----------------------------------------------------------
def statusInterpreter(status):
    """Generates a string according to the current value
       of the status variables.
    """
    return (
        f"width={status.grip_width / 10.0:.1f} mm "
        f"busy={status.busy} "
        f"grip_det={status.grip_det} "
        f"prox_l={status.prox_l / 10.0:.1f} mm "
        f"prox_r={status.prox_r / 10.0:.1f} mm "
        f"fta=({status.fx_l / 10.0:.1f}, {status.fy_l / 10.0:.1f}, {status.fz_l / 10.0:.1f}) N "
        f"ftb=({status.fx_r / 10.0:.1f}, {status.fy_r / 10.0:.1f}, {status.fz_r / 10.0:.1f}) N"
    )

#----------------------------------------------------------
def main(args=None):
    rclpy.init(args=args)

    onrobot_rg_status_listener = OnRobotRGStatusListener()

    rclpy.spin(onrobot_rg_status_listener)

    onrobot_rg_status_listener.destroy_node()
    rclpy.shutdown()


if __name__ == '__main__':
    main()
